// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.6.6. SEE SOURCE BELOW. !!
pragma solidity ^0.8.4;

interface IScore {
    error scoreOverLimit();
    event ScoreUpdate(address indexed student, uint256 indexed score);

    function changeScore(address _student, uint256 _score) external;

    function teacher() external view returns (address);
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[],"stateMutability":"payable","type":"constructor"},{"inputs":[],"name":"scoreOverLimit","type":"error"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"student","type":"address"},{"indexed":true,"internalType":"uint256","name":"score","type":"uint256"}],"name":"ScoreUpdate","type":"event"},{"inputs":[{"internalType":"address","name":"_student","type":"address"},{"internalType":"uint256","name":"_score","type":"uint256"}],"name":"changeScore","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"teacher","outputs":[{"internalType":"address payable","name":"","type":"address"}],"stateMutability":"view","type":"function"}]
*/
